services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ipc: host

    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-results:/app/allure-results
